name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up Gradle
      uses: gradle/gradle-build-action@v2

    - name: Build project (shadowJar)
      run: ./gradlew build

    - name: Create new tag
      run: |
        VERSION=$(./gradlew -q version)
        git tag "v$VERSION"
        git push origin "v$VERSION"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create GitHub release and upload JAR
      uses: softprops/action-gh-release@v1
      with:
        files: build/libs/*-all.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
