name: Deploy Ktor App

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout project
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'  
        distribution: 'temurin'

    - name: Set up Gradle
      uses: gradle/gradle-build-action@v2

    - name: Grant execute permission for Gradle wrapper
      run: chmod +x ./gradlew

    - name: Build project (shadowJar)
      run: ./gradlew build

    - name: Install sshpass
      run: sudo apt-get install sshpass

    - name: Copy jar to remote server using sshpass
      run: |
        sshpass -p '${{ secrets.SERVER_PASSWORD }}' scp build/libs/*-all.jar ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/home/root/ktor-app-all.jar
        
    - name: Run Ktor app remotely
      run: |
        ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'

        pkill -f 'ktor-app-all.jar' || true
        nohup java -jar /home/${{ secrets.SERVER_USER }}/ktor-app-all.jar > ktor.log 2>&1 &
        EOF
