name: Build and Release

on:
  push:
    branches:
      - main

permissions:
  contents: write  
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up Gradle
      uses: gradle/gradle-build-action@v2

    - name: Make gradlew executable
      run: chmod +x gradlew

    - name: Build project (shadowJar)
      run: ./gradlew build

    - name: Create random tag
      run: |
        TAG="v$(date +%Y%m%d%H%M%S)-$(openssl rand -hex 2)"
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git tag "$TAG"
        git push origin "$TAG"
        echo "TAG=$TAG" >> $GITHUB_ENV
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create GitHub release and upload JAR
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.TAG }}
        files: build/libs/*-all.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
